# Generated by Django 3.1.1 on 2020-09-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayitlar',
            name='Fotograf',
            field=models.ImageField(upload_to='', verbose_name='Add File'),
        ),
    ]
